GEO_ZONES = {
    "North America": ["US", "CA", "MX"],
    "Latin America": ["BR", "AR", "CO", "CL", "PE", "VE", "EC", "BO", "PY", "UY", "CR", "PA", "GT", "HN", "SV", "NI", "DO", "CU", "JM"],
    "Western Europe": ["GB", "DE", "FR", "NL", "BE", "CH", "AT", "IE", "DK", "SE", "NO", "FI", "PT", "ES", "IS", "LU", "MT"],
    "Eastern Europe": ["PL", "CZ", "SK", "HU", "RO", "BG", "HR", "SI", "RS", "BA", "ME", "AL", "MD", "UA", "BY", "RU", "EE", "LV", "LT"],
    "Middle East": ["AE", "SA", "QA", "KW", "BH", "OM", "JO", "LB", "IQ", "IR", "YE", "SY", "PS"],
    "South Asia": ["IN", "PK", "BD", "LK", "NP", "MV"],
    "East Asia": ["CN", "JP", "KR", "TW", "HK"],
    "Southeast Asia": ["SG", "MY", "TH", "ID", "PH", "VN", "MM", "KH", "BN"],
    "Central Asia": ["KZ", "UZ", "KG", "TM", "TJ", "AZ", "GE", "AM"],
    "Africa": ["ZA", "NG", "KE", "GH", "ET", "EG", "TZ", "UG", "SD", "MA", "TN", "DZ", "LY", "SN", "CM", "ZW", "ZM", "RW", "MZ", "AO"],
    "Oceania": ["AU", "NZ"]
}

COUNTRY_NAME_TO_CODE = {
    'afghanistan': 'AF', 'albania': 'AL', 'algeria': 'DZ', 'angola': 'AO',
    'argentina': 'AR', 'armenia': 'AM', 'australia': 'AU', 'austria': 'AT',
    'azerbaijan': 'AZ', 'bahrain': 'BH', 'bangladesh': 'BD', 'belarus': 'BY',
    'belgium': 'BE', 'belize': 'BZ', 'bolivia': 'BO', 'bosnia': 'BA',
    'brazil': 'BR', 'brunei': 'BN', 'bulgaria': 'BG', 'cambodia': 'KH',
    'cameroon': 'CM', 'canada': 'CA', 'chile': 'CL', 'china': 'CN',
    'colombia': 'CO', 'costa rica': 'CR', 'croatia': 'HR', 'cuba': 'CU',
    'cyprus': 'CY', 'czech': 'CZ', 'denmark': 'DK', 'dominican': 'DO',
    'ecuador': 'EC', 'egypt': 'EG', 'el salvador': 'SV', 'estonia': 'EE',
    'ethiopia': 'ET', 'finland': 'FI', 'france': 'FR', 'georgia': 'GE',
    'germany': 'DE', 'ghana': 'GH', 'greece': 'GR', 'guatemala': 'GT',
    'honduras': 'HN', 'hong kong': 'HK', 'hungary': 'HU', 'iceland': 'IS',
    'india': 'IN', 'indonesia': 'ID', 'iran': 'IR', 'iraq': 'IQ',
    'ireland': 'IE', 'israel': 'IL', 'italy': 'IT', 'jamaica': 'JM',
    'japan': 'JP', 'jordan': 'JO', 'kazakhstan': 'KZ', 'kenya': 'KE',
    'kuwait': 'KW', 'kyrgyzstan': 'KG', 'latvia': 'LV', 'lebanon': 'LB',
    'libya': 'LY', 'lithuania': 'LT', 'luxembourg': 'LU', 'malaysia': 'MY',
    'maldives': 'MV', 'malta': 'MT', 'mexico': 'MX', 'moldova': 'MD',
    'mongolia': 'MN', 'montenegro': 'ME', 'morocco': 'MA', 'mozambique': 'MZ',
    'myanmar': 'MM', 'nepal': 'NP', 'netherlands': 'NL', 'new zealand': 'NZ',
    'nicaragua': 'NI', 'nigeria': 'NG', 'norway': 'NO', 'oman': 'OM',
    'pakistan': 'PK', 'palestine': 'PS', 'panama': 'PA', 'paraguay': 'PY',
    'peru': 'PE', 'philippines': 'PH', 'poland': 'PL', 'portugal': 'PT',
    'qatar': 'QA', 'romania': 'RO', 'russia': 'RU', 'rwanda': 'RW',
    'saudi arabia': 'SA', 'saudi': 'SA', 'senegal': 'SN', 'serbia': 'RS',
    'singapore': 'SG', 'slovakia': 'SK', 'slovenia': 'SI', 'south africa': 'ZA',
    'south korea': 'KR', 'korea': 'KR', 'spain': 'ES', 'sri lanka': 'LK',
    'sudan': 'SD', 'sweden': 'SE', 'switzerland': 'CH', 'taiwan': 'TW',
    'tanzania': 'TZ', 'thailand': 'TH', 'tunisia': 'TN', 'turkey': 'TR',
    'turkiye': 'TR', 'uganda': 'UG', 'ukraine': 'UA',
    'uae': 'AE', 'united arab emirates': 'AE', 'emirates': 'AE',
    'uk': 'GB', 'united kingdom': 'GB', 'britain': 'GB', 'england': 'GB',
    'us': 'US', 'usa': 'US', 'united states': 'US', 'america': 'US',
    'uruguay': 'UY', 'uzbekistan': 'UZ', 'venezuela': 'VE', 'vietnam': 'VN',
    'zambia': 'ZM', 'zimbabwe': 'ZW'
}
